name: carline_flutter
description: A car marketplace

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  badges: ^2.0.3
  cupertino_icons: ^1.0.2
  fade_shimmer: ^2.2.0
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_gen: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.11
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  icons_plus: ^3.0.0
  local_auth: ^2.1.2
  nb_utils: ^4.6.21
  pinput: ^2.2.16
  riverpod_annotation: ^1.0.4
  tabler_icons: ^0.0.3

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: null
  flutter_gen_runner: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  riverpod_generator: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

# flutter gen configurations
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    #flare_flutter: true
    #rive: true
  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
    - assets/
