name: carline_flutter
description: A car marketplace

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_gen: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.11
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.0.2
  nb_utils: ^4.6.21
  riverpod_annotation: ^1.0.4

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: null
  flutter_gen_runner: ^5.0.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  riverpod_generator: ^1.0.4

# flutter gen configurations
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    #flare_flutter: true
    #rive: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
